# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Example function: roxygen2 documentation
#' 
#' This is the roxygen documentation of an example function.
#' 
#' @param a A double 
#' @param b A double 
#' 
#' @return A double a + b
#' 
#' @export 
#' 
docu_test_function <- function(a, b) {
    .Call('_rdoxygen_docu_test_function', PACKAGE = 'rdoxygen', a, b)
}

